### ISSUE TITLE
select box with choices-js plugin not working

### ISSUE THREAD

**Issue by MSouilah** [AdrianVillamayor/Wizard-JS#6]
Hi,

I'm still using your wizard, but when updating to new version 1.9.1 some bug appears working with the choices-js plugin.
In fact, it working good until version 1.7.6 but after it not working anymore.

**Describe the bug**
Select box not accessible, seems to be "disabled, frozen", it is not possible to select any choices.

**Expected behavior**
Select the element in the select box

Files:

in index.html
```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css"/>
<script src="https://cdn.jsdelivr.net/npm/choices.js/public/assets/scripts/choices.min.js"></script>

<div class="form-group">
    <label for="titleNoti">Action</label>
    <select class="form-control" name="actions" id="action1" >
        <option value="">Select one ...</option>
        <option value="0">Open 0</option>
        <option value="1">Open 1</option>
    </select>
</div>
```

in main.js
```
const action1 = document.getElementById("action1");
const list_action1 = new Choices(action1, 
	{
		allowHTML: true,
		searchEnabled: false
	}
);
```

**Comment by AdrianVillamayor** [comment]
Hi @MSouilah,

This happens because in versions > 1.8 the event system becomes the wizard element and not document.

So you call choices-js before it becomes accessible. That's why it doesn't allow you to act on it once it is displayed.

To solve this and to make it comfortable to use I have added an event in which it indicates you that the wizard is ready.

Here is your example updated to the new for you to see a way to assemble it => [Example code](https://jsfiddle.net/pwzjmbox/)

You have it all documented in the [Readme.me](https://github.com/AdrianVillamayor/Wizard-JS/blob/main/README.md) and in the [Changelog](https://github.com/AdrianVillamayor/Wizard-JS/compare/v1.9.1...v1.9.3).

I hope I solved your problem, anything else let me know.

Thank you very much for your help 🙌🏻.

**Comment by MSouilah** [comment]
Hi,
Thank you for your answer, actually it works great after initializing the wizard !! For some special elements I will use the 'readyWizard' event to be sure.

I post here a small piece of code to work with the choices-js plugin. With it, it is possible to highlight the combobox object if required. It has to be placed in the 'highlight: function (e, highlight = "error")'
```
var querycurrent = document.querySelectorAll(".choices");
loop = 0;
querycurrent.forEach(function(userItem) {
        var choices__input = userItem.querySelectorAll(".choices__input");
	if(choices__input[0].id == e.id){
		querycurrent[loop].classList.add(classHigh);
	}
	loop += 1;
});
```
